homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 0
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

frontend:

config: 

lyric:
  client_id: secret! honeywell_client_key
  client_secret: secret! honeywell_client_secret
    
remote:
  - platform: harmony
    name: Living_Room_Hub
    host: 192.168.50.33
    
http:
  api_password: !secret api_password
  ip_ban_enabled: False
  base_url: http://conedmiro.duckdns.org:8123

updater:

device_tracker:
  - platform: tile
    username: !secret tracker_login
    password: !secret tracker_password
    show_inactive: true

ios:

homekit:
      
panel_iframe:
  configurator:
    title: "Configurator"
    icon: mdi:wrench
    url: http://192.168.50.13:3218
  logger:
    title: "Logger"
    icon: mdi:card-text-outline
    url: http://192.168.50.13:4277
  nodered:
    title: "Node-Red"
    icon: mdi:sitemap
    url: https://192.168.50.13:1880
  pihole:
    title: "Pi-hole"
    icon: mdi:block-helper
    url: https://192.168.50.13:4865
  portainer:
    title: "Portainer"
    icon: mdi:docker
    url: https://192.168.50.13:9000
  terminal:
    title: "Terminal"
    icon: mdi:console
    url: https://192.168.50.13:7681
    
discovery:

logger:
  default: info
  
conversation:

cloud:

media_player:
  - platform: ps4
    host: http://192.169.50.13:3031
    ps4_ip: !secret ps4_address
    name: PlayStation 4
    local_store: games
  - platform: alexa
    email: !secret amazon_email
    password: !secret amazon_pass
    url: “amazon.com”
  - platform: yamaha
    host: !secret yamaha_address
    source_ignore:
      - AV1
      - AV2
      - AV3
      - AV4
      - AV5
      - AV6
      - Pandora
      - Rhapsody
      - SiriusXM
      - Spotify
      - Tuner
      - USB
      - V-AUX
    source_names:
      HDMI1: "Apple TV"
      HDMI2: "Playstation 4"
      HDMI3: "Wii U"
      HDMI4: "Cable"
      HDMI5: "Switch"
      AUDIO1: ""
      AUDIO2: ""
  
light: !include light.yaml
sensor: !include sensor.yaml

group: !include groups.yaml
# automation: !include automations.yaml
script: !include_dir_merge_named scripts/
