homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 0
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

frontend:

config:

system_health:

remote:
  - platform: harmony
    name: Living_Room_Hub
    host: 192.168.50.180
    
alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_pass
      url: amazon.com
    
http:
  api_password: !secret api_password
  ip_ban_enabled: False
  base_url: https://conedmiro.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:

device_tracker:
  - platform: tile
    username: !secret tracker_login
    password: !secret tracker_password
    show_inactive: true

ios:

homekit:
      
panel_iframe:
  configurator:
    title: "Configurator"
    icon: mdi:wrench
    url: https://192.168.50.13:3218
  ide:
    title: "IDE"
    icon: mdi:code-braces
    url: https://192.168.50.13:8321
  logger:
    title: "Logger"
    icon: mdi:card-text-outline
    url: https://192.168.50.13:4277
  nodered:
    title: "Node-Red"
    icon: mdi:sitemap
    url: https://192.168.50.13:1880
  pihole:
    title: "Pi-hole"
    icon: mdi:block-helper
    url: https://192.168.50.13:4865
  portainer:
    title: "Portainer"
    icon: mdi:docker
    url: https://192.168.50.13:9000
  terminal:
    title: "Terminal"
    icon: mdi:console
    url: https://192.168.50.13:7681
    
discovery:

logger:
  default: info
  
conversation:

cloud:

media_player: !include media_player.yaml
light: !include light.yaml
sensor: !include sensor.yaml

group: !include groups.yaml
shell_command: !include_dir_named shell/
script: !include scripts.yaml
