# - platform: ps4
#   host: http://192.169.50.13:3031
#   ps4_ip: !secret ps4_address
#   name: PlayStation 4
#   local_store: games
- platform: yamaha
  host: !secret yamaha_address
  source_ignore:
    - AV1
    - AV2
    - AV3
    - AV4
    - AV5
    - AV6
    - Pandora
    - Rhapsody
    - SiriusXM
    - Spotify
    - Tuner
    - USB
    - V-AUX
  source_names:
    HDMI1: "Apple TV"
    HDMI2: "Playstation 4"
    HDMI3: "Wii U"
    HDMI4: "Cable"
    HDMI5: "Switch"
    AUDIO1: ""
    AUDIO2: ""
# - platform: androidtv
#   host: 192.168.50.49
#   name: "Fire Stick 4K"
#   adb_server_ip: 127.0.0.1
#   adb_server_port: 5037