resources:
  - type: js
    url: /local/plan-coordinates.js?v=2
title: Mike's Apartment
views:
  - badges: []
    cards:
    icon: 'mdi:home-assistant'
    id: floorplan
    panel: true
    theme: dark-mode
    title: Floorplan
      - elements:
          - entity: sensor.august
            state_image:
              locked: /local/lock.png
              unlocked: /local/unlock.png
            style:
              color: black
              left: 10%
              top: 86%
            type: image
          - entity: sensor.august
            state_image:
              locked: /local/cam-left.png
              unlocked: /local/cam-left.png
            style:
              color: black
              left: 15%
              top: 82%
            type: image
          - entity: sensor.august
            state_image:
              locked: /local/cam-right.png
              unlocked: /local/cam-right.png
            style:
              color: black
              left: 31%
              top: 71%
            type: image
          - entity: sensor.living_room_multi_temp
            hold_action: more-info
            style:
              color: '#44739e'
              font-weight: bold
              left: 50.5%
              top: 73%
            tap_action: more-info
            type: state-label
          - entity: light.entrance
            hold_action: more-info
            style:
              left: 16%
              top: 86%
            tap_action: toggle
            type: state-icon
          - entity: sensor.living_room_multi_motion
            state_image:
              active: /local/active.png
              inactive: /local/inactive.png
            style:
              color: black
              left: 42%
              top: 71%
            type: image
          - entity: light.bar
            hold_action: more-info
            style:
              left: 42%
              top: 65%
            tap_action: toggle
            type: state-icon
          - entity: light.dining
            hold_action: more-info
            style:
              left: 45.5%
              top: 84.5%
            tap_action: toggle
            type: state-icon
          - entity: light.hall
            hold_action: more-info
            style:
              left: 56.5%
              top: 41%
            tap_action: toggle
            type: state-icon
          - entity: light.corner
            hold_action: more-info
            style:
              left: 90%
              top: 89%
            tap_action: toggle
            type: state-icon
          - entity: sensor.litter_box_2
            state_image:
              closed: /local/clean_closed.png
              open: /local/clean_open.png
            style:
              left: 89.5%
              top: 84%
            type: image
          - entity: light.far_corner
            hold_action: more-info
            style:
              left: 90%
              top: 55%
            tap_action: toggle
            type: state-icon
          - entity: media_player.yamaha_receiver
            type: icon
            icon: mdi:audio-video
            style:
              color: '#44739e'
              font-weight: bold
              left: 72%
              top: 54%
          - entity: media_player.playstation_4
            type: icon
            icon: mdi:playstation
            style:
              color: '#44739e'
              font-weight: bold
              left: 75%
              top: 54%
          - entity: media_player.apartment
            type: icon
            icon: mdi:apple
            style:
              color: '#44739e'
              font-weight: bold
              left: 78%
              top: 54%
          - entity: remote.living_room_hub
            type: icon
            icon: mdi:remote
            style:
              color: '#44739e'
              font-weight: bold
              left: 81%
              top: 54%
          - entity: sensor.fridge
            state_image:
              closed: /local/fridge_closed2.png
              open: /local/fridge_open2.png
            style:
              left: 32%
              top: 44%
            type: image
          - entity: sensor.freezer
            state_image:
              closed: /local/freezer_closed2.png
              open: /local/freezer_open2.png
            style:
              left: 32%
              top: 44%
            type: image
          - entity: sensor.freezer_temperature_sensor
            hold_action: more-info
            style:
              color: '#44739e'
              font-weight: bold
              left: 32.5%
              top: 30.5%
            tap_action: more-info
            type: state-label
          - entity: sensor.august
            state_image:
              locked: /local/cam-left.png
              unlocked: /local/cam-left.png
            style:
              color: black
              left: 37%
              top: 47%
            type: image
          - entity: light.bathroom_right
            hold_action: more-info
            style:
              left: 43%
              top: 15%
            tap_action: toggle
            type: state-icon
          - entity: light.bathroom_center
            hold_action: more-info
            style:
              left: 43%
              top: 20%
            tap_action: toggle
            type: state-icon
          - entity: light.bathroom_left
            hold_action: more-info
            style:
              left: 43%
              top: 25%
            tap_action: toggle
            type: state-icon
          - entity: sensor.bathroom_multi_motion
            state_image:
              active: /local/active.png
              inactive: /local/inactive.png
            style:
              color: black
              left: 49%
              top: 20%
            type: image
          - entity: sensor.bathroom_multi_temp
            hold_action: more-info
            style:
              color: '#44739e'
              font-weight: bold
              left: 47%
              top: 12%
            tap_action: more-info
            type: state-label
          - entity: sensor.bedroom_temperature_sensor
            hold_action: more-info
            style:
              color: '#44739e'
              font-weight: bold
              left: 76%
              top: 37.5%
            tap_action: more-info
            type: state-label
          - entity: light.bed_right
            hold_action: more-info
            style:
              left: 89.5%
              top: 10.5%
            tap_action: toggle
            type: state-icon
          - entity: light.bed_left
            hold_action: more-info
            style:
              left: 67.5%
              top: 10.5%
            tap_action: toggle
            type: state-icon
          - entity: light.bed_left
            hold_action: more-info
            style:
              left: 77%
              top: 31%
            tap_action: toggle
            type: state-icon
          - entity: sensor.bedroom_motion
            state_image:
              active: /local/active.png
              inactive: /local/inactive.png
            style:
              color: black
              left: 65%
              top: 20%
            type: image
          - entity: light.bed_left
            hold_action: more-info
            style:
              left: 90%
              top: 47%
            tap_action: toggle
            type: state-icon
        image: /local/floorplan2.png
        panel: true
        scale: 65%
        type: picture-elements
  - cards:
    id: home
    show_header_toggle: true
    title: Home
      - entity: media_player.apartment
        type: media-control
      - entity: media_player.yamaha_receiver
        type: media-control
      - entities:
          - group.august
        show_header_toggle: false
        title: August Smart Lock
        type: entities
      - entities:
          - sensor.living_room_multi_humid
          - sensor.living_room_multi_lume
          - sensor.living_room_multi_motion
          - sensor.living_room_multi_temp
        show_header_toggle: false
        title: Living Room Multi Sensor
        type: entities
      - entities:
          - group.living_room_lights
          - group.late_lights
          - group.right_side_lights
        show_header_toggle: false
        title: Living Room Lights
        type: entities
  - cards:
    id: bathroom
    show_header_toggle: true
    title: Bathroom
      - entities:
          - entity: sensor.bathroom_multi_humid
          - sensor.bathroom_multi_lume
          - sensor.bathroom_multi_motion
          - sensor.bathroom_multi_temp
        show_header_toggle: false
        title: Bathroom Multi Sensor
        type: entities
      - entities:
          - sensor.bathroom_motion
        show_header_toggle: false
        title: Bathroom Motion Sensor
        type: entities
      - entities:
          - group.bathroom_lights
        show_header_toggle: false
        title: Bathroom Lights
        type: entities
  - cards:
    id: kitchen
    show_header_toggle: true
    title: Kitchen
      - entities:
          - sensor.fridge
          - sensor.freezer
          - sensor.freezer_temperature_sensor
        type: entities
